CREATE TYPE license_category AS ENUM ('A','A1','A2','B','BE','C','D');
CREATE TYPE lesson_type AS ENUM ('practical','theoretical');

CREATE TABLE person (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        pnc VARCHAR(13) NOT NULL UNIQUE,
                        dob DATE NOT NULL,
                        first_name VARCHAR(50) NOT NULL,
                        last_name VARCHAR(50) NOT NULL,
                        email_address VARCHAR(255) NOT NULL UNIQUE,
                        phone_number VARCHAR(20) NOT NULL UNIQUE,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP
);

CREATE UNIQUE INDEX person_pnc_uq ON person (pnc);
CREATE UNIQUE INDEX person_email_uq ON person (email_address);
CREATE UNIQUE INDEX person_phone_uq ON person (phone_number);

CREATE TABLE student (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         person_id INT NOT NULL UNIQUE,
                         is_compliant BOOL NOT NULL DEFAULT FALSE,
                         created_at TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP
);

CREATE UNIQUE INDEX student_person_id_uq ON student (person_id);

CREATE TABLE instructor (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            person_id INT NOT NULL UNIQUE,
                            license_category license_category NOT NULL,
                            is_compliant BOOL NOT NULL DEFAULT FALSE,
                            is_active BOOL NOT NULL DEFAULT TRUE,
                            created_at TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP
);

CREATE UNIQUE INDEX instructor_person_id_uq ON instructor (person_id);
CREATE INDEX instructor_license_category_idx ON instructor (license_category);

CREATE TABLE vehicle (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         registration_number VARCHAR NOT NULL UNIQUE,
                         license_category license_category NOT NULL,
                         min_age INT NOT NULL,
                         make VARCHAR NOT NULL,
                         model VARCHAR NOT NULL,
                         year INT NOT NULL,
                         transmission VARCHAR NOT NULL,
                         fuel_type VARCHAR NOT NULL,
                         is_active BOOL NOT NULL DEFAULT TRUE,
                         created_at TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP
);

CREATE UNIQUE INDEX vehicle_registration_number_uq ON vehicle (registration_number);
CREATE INDEX vehicle_license_category_idx ON vehicle (license_category);
CREATE INDEX vehicle_is_active_idx ON vehicle (is_active);

CREATE TABLE enrollment (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            student_id INT NOT NULL,
                            instructor_id INT NOT NULL,
                            vehicle_id INT NOT NULL,
                            created_at TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP
);

CREATE INDEX enrollment_student_id_idx ON enrollment (student_id);
CREATE INDEX enrollment_instructor_id_idx ON enrollment (instructor_id);
CREATE INDEX enrollment_vehicle_id_idx ON enrollment (vehicle_id);
CREATE INDEX enrollment_created_at_idx ON enrollment (created_at);

CREATE TABLE lesson (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        enrollment_id INT NOT NULL,
                        count INT NOT NULL,
                        type lesson_type NOT NULL,
                        date DATE NOT NULL,
                        location VARCHAR NOT NULL,
                        completed BOOL NOT NULL DEFAULT FALSE,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP
);

CREATE INDEX lesson_enrollment_id_idx ON lesson (enrollment_id);
CREATE UNIQUE INDEX lesson_enrollment_count_uq ON lesson (enrollment_id, count);
CREATE INDEX lesson_date_idx ON lesson (date);

CREATE TABLE exam (
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      enrollment_id INT NOT NULL,
                      date DATE NOT NULL,
                      hour TIME NOT NULL,
                      location VARCHAR NOT NULL,
                      completed BOOL NOT NULL DEFAULT FALSE,
                      created_at TIMESTAMP NOT NULL,
                      updated_at TIMESTAMP
);

CREATE INDEX exam_enrollment_id_idx ON exam (enrollment_id);
CREATE INDEX exam_date_idx ON exam (date);


